# Generated by Django 3.1.2 on 2021-01-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_remove_book_users'),
        ('users', '0002_profile_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(to='booklist.Book'),
        ),
    ]
