# Generated by Django 3.1.5 on 2021-02-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210222_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='requestUserId',
            new_name='followerUser',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='acceptingUserId',
            new_name='followingUser',
        ),
    ]
